/**
 * Conversion benchmark: runs every asset in samples/manifest.json through the same Blender
 * conversion the worker uses, and writes the results table to docs/conversion_results.md.
 *
 *   npm run bench                      convert everything, rewrite the table
 *   npm run bench -- --check           also fail if the median is below docs/conversion_baseline.json
 *   npm run bench -- --update-baseline record this run's median as the new baseline
 *
 * Every size-reduction figure quoted in the README comes from this script's output.
 */
import { inspectGlb, type GlbInfo } from '@splatbox/shared'
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { cpus } from 'node:os'
import { basename, extname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { blenderVersion, findBlender } from '../worker/src/blender/locate'
import { createBlenderTools, DEFAULT_CONVERT_OPTIONS, type ConvertReport } from '../worker/src/blender/scripts'

interface Sample {
  file: string
  group: 'third-party' | 'in-house'
  content: string
  license: string
  credit: string
}

interface Row extends Sample {
  bytesBefore: number
  bytesAfter: number
  reductionPct: number
  triangles: number
  textures: number
  resizedTextures: number
  seconds: number
  after: GlbInfo
  report: ConvertReport
}

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const ASSETS = join(ROOT, 'samples/assets')
const OUT = join(ROOT, '.bench')
const DOCS = join(ROOT, 'docs')
const BASELINE = join(DOCS, 'conversion_baseline.json')

function median(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b)
  const mid = Math.floor(sorted.length / 2)
  return sorted.length % 2 === 1 ? sorted[mid]! : (sorted[mid - 1]! + sorted[mid]!) / 2
}

const kb = (bytes: number) => (bytes / 1024).toLocaleString('en-US', { maximumFractionDigits: 1, minimumFractionDigits: 1 })
const pct = (value: number) => `${value.toFixed(1)}%`

/** Things a conversion must not lose. A violation fails the benchmark regardless of the sizes. */
function integrityProblems(row: Row): string[] {
  const problems: string[] = []
  const { after, report } = row
  if (after.triangles !== report.before.triangles) problems.push(`triangles ${report.before.triangles} -> ${after.triangles}`)
  if (after.dracoPrimitives !== after.primitives) problems.push(`${after.primitives - after.dracoPrimitives} primitives not Draco-compressed`)
  if (after.animations.length !== report.before.animations) problems.push(`animations ${report.before.animations} -> ${after.animations.length}`)
  if (after.skins !== report.before.armatures) problems.push(`skins ${report.before.armatures} -> ${after.skins}`)
  if (after.textures !== report.before.textures) problems.push(`textures ${report.before.textures} -> ${after.textures}`)
  return problems
}

function renderMarkdown(rows: Row[], blender: string): string {
  const all = median(rows.map((r) => r.reductionPct))
  const thirdParty = median(rows.filter((r) => r.group === 'third-party').map((r) => r.reductionPct))
  const o = DEFAULT_CONVERT_OPTIONS
  const q = rows[0]!.report.settings.quantization as Record<string, number>
  const lines = [
    '# Conversion results',
    '',
    '<!-- Generated by scripts/bench_convert.ts (npm run bench). Do not edit by hand. -->',
    '',
    `**Median size reduction: ${pct(all)}** over ${rows.length} assets ` +
      `(${pct(thirdParty)} over the ${rows.filter((r) => r.group === 'third-party').length} third-party assets alone).`,
    '',
    '| Asset | Content | Before (KB) | After (KB) | Reduction | Triangles | Textures | Convert (s) |',
    '| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |',
    ...rows.map((r) => {
      const textures = r.resizedTextures > 0 ? `${r.textures} (${r.resizedTextures} resized)` : String(r.textures)
      return `| \`${r.file}\` | ${r.content} | ${kb(r.bytesBefore)} | ${kb(r.bytesAfter)} | ${pct(r.reductionPct)} | ${r.triangles.toLocaleString('en-US')} | ${textures} | ${r.seconds.toFixed(2)} |`
    }),
    '',
    `Smallest reduction ${pct(Math.min(...rows.map((r) => r.reductionPct)))}, largest ${pct(Math.max(...rows.map((r) => r.reductionPct)))}. ` +
      'Triangle, texture, skin and animation counts are checked to be identical before and after for every asset.',
    '',
    '## Settings',
    '',
    `- Geometry: Draco mesh compression (\`KHR_draco_mesh_compression\`), level ${rows[0]!.report.settings.draco_level}; ` +
      `quantization bits: position ${q.position}, normal ${q.normal}, texture coordinate ${q.texcoord}, colour ${q.color}, generic (skin weights) ${q.generic}.`,
    `- Textures: longest side capped at ${o.maxTexture} px; re-encoded as ${o.textureFormat === 'webp' ? 'WebP (`EXT_texture_webp`)' : o.textureFormat.toUpperCase()} at quality ${o.textureQuality}.`,
    '- Animations: source keyframes are exported as they are (no per-frame baking); skins are kept.',
    '- Cameras, lights and childless empties are removed.',
    '',
    '## Environment',
    '',
    `- Blender ${blender}`,
    `- ${cpus()[0]?.model ?? 'unknown CPU'}, ${process.platform} ${process.arch}`,
    '- Convert time is wall-clock for one headless Blender run per asset, including Blender start-up.',
    '',
    'Sample set composition and licenses: [samples/README.md](../samples/README.md).',
    '',
  ]
  return lines.join('\n')
}

async function main(): Promise<void> {
  const args = new Set(process.argv.slice(2))
  if (existsSync(join(ROOT, '.env'))) process.loadEnvFile(join(ROOT, '.env'))
  const blenderBin = findBlender(process.env.BLENDER_BIN || undefined)
  const blender = createBlenderTools(blenderBin)
  const manifest = JSON.parse(readFileSync(join(ROOT, 'samples/manifest.json'), 'utf8')) as { benchmark: Sample[] }
  mkdirSync(OUT, { recursive: true })
  mkdirSync(DOCS, { recursive: true })

  const rows: Row[] = []
  for (const sample of manifest.benchmark) {
    const input = join(ASSETS, sample.file)
    if (!existsSync(input)) throw new Error(`${sample.file} is missing from samples/assets; run \`npm run samples\` first`)
    const output = join(OUT, `${basename(sample.file, extname(sample.file))}.glb`)
    const started = performance.now()
    const report = await blender.convert(input, output)
    const seconds = (performance.now() - started) / 1000
    const after = inspectGlb(readFileSync(output))
    const bytesBefore = statSync(input).size
    const row: Row = {
      ...sample,
      bytesBefore,
      bytesAfter: after.bytes,
      reductionPct: (1 - after.bytes / bytesBefore) * 100,
      triangles: after.triangles,
      textures: after.textures,
      resizedTextures: report.resized_textures.length,
      seconds,
      after,
      report,
    }
    rows.push(row)
    console.log(`${sample.file.padEnd(22)} ${kb(bytesBefore).padStart(10)} KB -> ${kb(after.bytes).padStart(8)} KB  ${pct(row.reductionPct).padStart(6)}  ${seconds.toFixed(2)}s`)
  }

  const medianAll = median(rows.map((r) => r.reductionPct))
  const medianThirdParty = median(rows.filter((r) => r.group === 'third-party').map((r) => r.reductionPct))
  console.log(`\nmedian reduction: ${pct(medianAll)} over ${rows.length} assets (${pct(medianThirdParty)} third-party only)`)

  writeFileSync(join(DOCS, 'conversion_results.md'), renderMarkdown(rows, blenderVersion(blenderBin)))
  console.log('wrote docs/conversion_results.md')

  let failed = false
  for (const row of rows) {
    for (const problem of integrityProblems(row)) {
      console.error(`INTEGRITY ${row.file}: ${problem}`)
      failed = true
    }
  }

  if (args.has('--update-baseline')) {
    // Encoders differ slightly between platforms, so the check allows this much slack below the baseline.
    const baseline = { medianReductionPct: Number(medianAll.toFixed(2)), tolerancePct: 0.5, assets: rows.length }
    writeFileSync(BASELINE, JSON.stringify(baseline, null, 2) + '\n')
    console.log(`wrote docs/conversion_baseline.json (${baseline.medianReductionPct}%)`)
  }

  if (args.has('--check')) {
    const baseline = JSON.parse(readFileSync(BASELINE, 'utf8')) as { medianReductionPct: number; tolerancePct: number; assets: number }
    const floor = baseline.medianReductionPct - baseline.tolerancePct
    if (rows.length !== baseline.assets) {
      console.error(`CHECK FAILED: ${rows.length} assets converted, the baseline was recorded on ${baseline.assets}`)
      failed = true
    }
    if (medianAll < floor) {
      console.error(`CHECK FAILED: median ${pct(medianAll)} is below the baseline ${baseline.medianReductionPct}% (floor ${floor.toFixed(2)}%)`)
      failed = true
    } else {
      console.log(`check passed: median ${pct(medianAll)} >= floor ${floor.toFixed(2)}% (baseline ${baseline.medianReductionPct}%)`)
    }
  }
  if (failed) process.exit(1)
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err)
  process.exit(1)
})
